In [33]:
from sigmaepsilon.math.linalg import Vector, ReferenceFrame, CartesianFrame
import numpy as np

In [34]:
A = ReferenceFrame(name='A', axes=np.eye(3))
B = A.orient_new('Body', [0, 0, 90*np.pi/180], 'XYZ', name='B')
B.dcm()

array([[ 6.123234e-17,  1.000000e+00,  0.000000e+00],
       [-1.000000e+00,  6.123234e-17,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [35]:
v = Vector([0.0, 1.0, 0.0], frame=A)
v.show(B)

array([1.000000e+00, 6.123234e-17, 0.000000e+00])

In [36]:
v.dual()

Array([0., 1., 0.])

In [37]:
v.orient('Body', [0, 0, -90*np.pi/180], 'XYZ')
v.show(B)

array([ 1.2246468e-16, -1.0000000e+00,  0.0000000e+00])

In [38]:
v.show()

array([1.000000e+00, 6.123234e-17, 0.000000e+00])

In [39]:
# the original frame    
A = ReferenceFrame(dim=3, axes=np.eye(3))

# the original vector
vA = Vector([1., 0., 0.], frame=A)

# random rotation
amounts = [0., 0., 0.]
amounts[2] = 90 * np.pi / 180
B = A.orient_new('Body', amounts, 'XYZ')

In [40]:
vA.show()

array([1., 0., 0.])

In [41]:
vA.show(A)

array([1., 0., 0.])

In [42]:
vA.show(B)

array([ 6.123234e-17, -1.000000e+00,  0.000000e+00])

In [43]:
vA2 = Vector(vA.show(B), frame=B)

In [44]:
vA2.show(A)

array([1., 0., 0.])

In [45]:
vA2.show()

array([1., 0., 0.])

In [46]:
vA2.array

Array([ 6.123234e-17, -1.000000e+00,  0.000000e+00])

In [47]:
vA2.frame

array([[ 6.123234e-17,  1.000000e+00,  0.000000e+00],
       [-1.000000e+00,  6.123234e-17,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [48]:
vA2.show()

array([1., 0., 0.])

In [49]:
A = ReferenceFrame(name='A', axes=np.eye(3))
B = A.orient_new('Body', [0, 0, 90*np.pi/180], 'XYZ', name='B')

In [50]:
A.Gram()

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
A.metric_tensor()

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
B.metric_tensor()

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
type(B)

sigmaepsilon.math.linalg.frame.ReferenceFrame

In [54]:
list(B._weakrefs.values())

[Array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])]

In [55]:
B *= 2
B.metric_tensor()

Array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [56]:
B

Array([[ 1.2246468e-16,  2.0000000e+00,  0.0000000e+00],
       [-2.0000000e+00,  1.2246468e-16,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  2.0000000e+00]])

In [57]:
B.dual()

Array([[ 3.061617e-17,  5.000000e-01,  0.000000e+00],
       [-5.000000e-01,  3.061617e-17,  0.000000e+00],
       [-0.000000e+00,  0.000000e+00,  5.000000e-01]])

In [58]:
B.dual().dual()

Array([[ 1.2246468e-16,  2.0000000e+00,  0.0000000e+00],
       [-2.0000000e+00,  1.2246468e-16,  0.0000000e+00],
       [-0.0000000e+00,  0.0000000e+00,  2.0000000e+00]])

In [59]:
B.volume()

7.999999999999998

In [60]:
1/B.volume(), B.dual().volume()

(0.12500000000000003, 0.12500000000000003)

In [61]:
A = ReferenceFrame(axes=np.eye(3))
axes = np.eye(3)
axes[1] = [-1/2, 1/2, 0.]
B = ReferenceFrame(axes=axes)
vA = Vector([1.0, 1.0, 1.0], frame=A)
vA.show(B)

array([2., 2., 1.])

In [62]:
aB = vA.show(B)
vB = Vector(aB, frame=B)
vB.show(A)

array([1., 1., 1.])

In [63]:
if B.is_independent:
    print(True)
else:
    print(False)

True


In [64]:
f = CartesianFrame(dim=3)
f *= 2
f

Array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [65]:
f = CartesianFrame(dim=3)
f + 2

Array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

In [66]:
np.dot(f,f)

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
import gc, sys
from sigmaepsilon.math.linalg import Vector, ReferenceFrame, CartesianFrame
import numpy as np

In [68]:
A = ReferenceFrame(axes=np.eye(3))
vA = Vector([1.0, 1.0, 1.0], frame=A)

In [69]:
id(A)

2236215319888

In [70]:
list(A._weakrefs.values())

[Array([1., 1., 1.])]

In [71]:
A *= 2

In [72]:
A

Array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [73]:
id(A)

2236215319888

In [74]:
list(A._weakrefs.values())

[Array([0.5, 0.5, 0.5])]

In [75]:
id(A)

2236215319888

In [76]:
arr = 2*np.eye(3)
B = np.sqrt(arr, out=A)

In [77]:
A

Array([[1.41421356, 0.        , 0.        ],
       [0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 1.41421356]])

In [78]:
id(B)

2236215685376

In [79]:
np.sqrt(A)

Array([[1.18920712, 0.        , 0.        ],
       [0.        , 1.18920712, 0.        ],
       [0.        , 0.        , 1.18920712]])

In [80]:
id(A)

2236215319888

In [81]:
A *= 2

In [82]:
arr = np.array([1, 1])

In [83]:
id(arr)

2236217091312

In [84]:
arr *= 2

In [85]:
id(A._array)

2236216881344

In [86]:
A._array *= 2