In [38]:
import numpy as np

nx, ny, nz = (10, 10, 10)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
z = np.linspace(0, 1, nz)
xv, yv, zv = np.meshgrid(x, y, z)
points = np.stack([xv.flatten(), yv.flatten(), zv.flatten()], axis=-1)
values = np.random.rand(nx*ny*nz)
del xv, yv, zv, x, y, z

In [39]:
from sigmaepsilon.math.approx import moving_least_squares
from sigmaepsilon.math.approx import ConstantWeightFunction

w = ConstantWeightFunction(core=[0.0, 0.0, 0.0], supportdomain=[0.5, 0.5, 0.5])
approx = moving_least_squares(points, values, deg=1, order=2, w=w)

f, fdx, fdy, fdz, fdxx, fdyy, fdzz, fdxy, fdxz, fdyz = approx([0, 0, 0])
approx([0, 0, 0])

(array([0.44807146]),
 array([-0.02806849]),
 array([0.1835602]),
 array([0.03715389]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]))

In [40]:
i = 10
approx(points[i])[0], values[i]

(array([0.45975074]), 0.7322021202391502)