In [7]:
import numpy as np

nx, ny, nz = (10, 10, 10)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
z = np.linspace(0, 1, nz)
xv, yv, zv = np.meshgrid(x, y, z)
points = np.stack([xv.flatten(), yv.flatten(), zv.flatten()], axis=-1)
values = np.random.rand(nx*ny*nz)
del xv, yv, zv, x, y, z

In [8]:
from sigmaepsilon.math.approx import moving_least_squares
from sigmaepsilon.math.approx import ConstantWeightFunction

w = ConstantWeightFunction(core=[0.0, 0.0, 0.0], supportdomain=[0.5, 0.5, 0.5])
approx = moving_least_squares(points, values, deg=1, order=2, w=w)

f, fdx, fdy, fdz, fdxx, fdyy, fdzz, fdxy, fdxz, fdyz = approx([0, 0, 0])
approx([0, 0, 0])

(array([0.34213131]),
 array([0.20802815]),
 array([0.14990781]),
 array([0.27132217]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]))

In [9]:
i = 10
approx(points[i])[0], values[i]

(array([0.39300874]), 0.9407842933480457)

In [10]:
from sigmaepsilon.math.approx import MLSApproximator

approximator = MLSApproximator()
values = np.ones((len(values), 3))
approximator.fit(points, values, points)

In [11]:
approximator.neighbours

array([[  0,  10, 100,   1],
       [  1, 101,  11,   2],
       [  2,   1, 102,   3],
       ...,
       [997, 996, 987, 998],
       [998, 997, 898, 988],
       [999, 899, 989, 998]], dtype=int64)

In [12]:
approximator.approximate(points)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       ...,
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])