In [22]:
from sigmaepsilon.math.linalg import Vector, ReferenceFrame, CartesianFrame
import numpy as np

In [23]:
A = ReferenceFrame(name='A', axes=np.eye(3))
B = A.orient_new('Body', [0, 0, 90*np.pi/180], 'XYZ', name='B')
B.dcm()

Array([[ 6.123234e-17,  1.000000e+00,  0.000000e+00],
       [-1.000000e+00,  6.123234e-17,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [24]:
v = Vector([0.0, 1.0, 0.0], frame=A)
v.show(B)

array([1.000000e+00, 6.123234e-17, 0.000000e+00])

In [25]:
v.dual()

Vector([0., 1., 0.])

In [26]:
v.orient('Body', [0, 0, -90*np.pi/180], 'XYZ')
v.show(B)

array([ 1.2246468e-16, -1.0000000e+00,  0.0000000e+00])

In [27]:
v.show()

array([1.000000e+00, 6.123234e-17, 0.000000e+00])

In [28]:
# the original frame    
A = ReferenceFrame(dim=3, axes=np.eye(3))

# the original vector
vA = Vector([1., 0., 0.], frame=A)

# random rotation
amounts = [0., 0., 0.]
amounts[2] = 90 * np.pi / 180
B = A.orient_new('Body', amounts, 'XYZ')

In [29]:
vA.show()

array([1., 0., 0.])

In [30]:
vA.show(A)

array([1., 0., 0.])

In [31]:
vA.show(B)

array([ 6.123234e-17, -1.000000e+00,  0.000000e+00])

In [32]:
vA2 = Vector(vA.show(B), frame=B)

In [33]:
vA2.show(A)

array([1., 0., 0.])

In [34]:
vA2.show()

array([1., 0., 0.])

In [35]:
vA2.array

Array([ 6.123234e-17, -1.000000e+00,  0.000000e+00])

In [36]:
vA2.frame

Array([[ 6.123234e-17,  1.000000e+00,  0.000000e+00],
       [-1.000000e+00,  6.123234e-17,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [37]:
vA2.show()

array([1., 0., 0.])

In [38]:
A = ReferenceFrame(name='A', axes=np.eye(3))
B = A.orient_new('Body', [0, 0, 90*np.pi/180], 'XYZ', name='B')

In [39]:
A.Gram()

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
A.metric_tensor()

Tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [41]:
B.metric_tensor()

Tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [42]:
type(B)

sigmaepsilon.math.linalg.frame.ReferenceFrame

In [44]:
list(B._weakrefs.values())

[Tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]])]

In [21]:
B *= 2
B.metric_tensor()

TypeError: orientnew() got an unexpected keyword argument 'dcm'

In [ ]:
B

Array([[ 1.2246468e-16,  2.0000000e+00,  0.0000000e+00],
       [-2.0000000e+00,  1.2246468e-16,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  2.0000000e+00]])

In [ ]:
B.dual()

Array([[ 3.061617e-17,  5.000000e-01,  0.000000e+00],
       [-5.000000e-01,  3.061617e-17,  0.000000e+00],
       [-0.000000e+00,  0.000000e+00,  5.000000e-01]])

In [ ]:
B.dual().dual()

Array([[ 1.2246468e-16,  2.0000000e+00,  0.0000000e+00],
       [-2.0000000e+00,  1.2246468e-16,  0.0000000e+00],
       [-0.0000000e+00,  0.0000000e+00,  2.0000000e+00]])

In [ ]:
B.volume()

7.999999999999998

In [ ]:
1/B.volume(), B.dual().volume()

(0.12500000000000003, 0.12500000000000003)

In [ ]:
A = ReferenceFrame(axes=np.eye(3))
axes = np.eye(3)
axes[1] = [-1/2, 1/2, 0.]
B = ReferenceFrame(axes=axes)
vA = Vector([1.0, 1.0, 1.0], frame=A)
vA.show(B)

array([2., 2., 1.])

In [ ]:
aB = vA.show(B)
vB = Vector(aB, frame=B)
vB.show(A)

array([1., 1., 1.])

In [ ]:
if B.is_independent():
    print(True)
else:
    print(False)

True


In [ ]:
f = CartesianFrame(dim=3)
f *= 2
f

Array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [ ]:
f = CartesianFrame(dim=3)
f + 2

Array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

In [ ]:
np.dot(f,f)

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import gc, sys
from sigmaepsilon.math.linalg import Vector, ReferenceFrame, CartesianFrame
import numpy as np

In [ ]:
A = ReferenceFrame(axes=np.eye(3))
vA = Vector([1.0, 1.0, 1.0], frame=A)

In [ ]:
id(A)

2756036905232

In [ ]:
list(A._weakrefs.values())

[Vector([1., 1., 1.])]

In [ ]:
A *= 2

In [ ]:
A

Array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [ ]:
id(A)

2756036905232

In [ ]:
list(A._weakrefs.values())

[Vector([1., 1., 1.])]

In [ ]:
id(A)

2756036905232

In [ ]:
arr = 2*np.eye(3)
B = np.sqrt(arr, out=A)

In [ ]:
A

Array([[1.41421356, 0.        , 0.        ],
       [0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 1.41421356]])

In [ ]:
id(B)

2756036903072

In [ ]:
np.sqrt(A)

Array([[1.18920712, 0.        , 0.        ],
       [0.        , 1.18920712, 0.        ],
       [0.        , 0.        , 1.18920712]])

In [ ]:
id(A)

2756036905232

In [ ]:
A *= 2

In [ ]:
arr = np.array([1, 1])

In [ ]:
id(arr)

2756036565872

In [ ]:
arr *= 2

In [ ]:
id(A._array)

2756036944704

In [ ]:
A._array *= 2